# Generated by Django 5.1.4 on 2024-12-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationmodel",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
