# Generated by Django 5.1.4 on 2025-01-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["-pub_time"]},
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="blogcategory",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatars/default.jpg", upload_to="avatars/"
            ),
        ),
        migrations.AlterModelTable(
            name="blog",
            table=None,
        ),
        migrations.AlterModelTable(
            name="blogcategory",
            table=None,
        ),
        migrations.AlterModelTable(
            name="blogcomment",
            table=None,
        ),
    ]
